### ISSUE TITLE
Stove name in config cannot be retrieved from API

### ISSUE THREAD

**Issue by brufal** [securechicken/homebridge-micronova-agua-iot-stove#5] opened 2021-04-28 20:34 UTC
Hello all,
in the following screenshot you can see the problem i meet with my log i have try many name, but it never work!! come someone help me.

I precise that the name of my Piazzetta in my house is Maison, and i have try with P963 18.0 and also with the mac adress of my micronova agua iot

Thanks in advance for your help @securechicken 
![Capture d’écran 2021-04-28 à 22 29 54](https://user-images.githubusercontent.com/83335117/116469113-034c4400-a872-11eb-90c3-33b8b158df93.png)

**Comment by brufal** [comment] 2021-04-28 20:48
i don't know if the following other screenshot can help or not.

[REDACTED DUE TO AUTHENTICATION SECRET IN PROVIDED FILE]

**Comment by securechicken** [comment] 2021-04-28 22:54
Hi @brufal 

In order to start investigating your issue, please provide the following additional information:
|Item|Your information|
|---|---|
|**Homebridge Version**||
|**Plugin version**||
|**Stove brand/mobile app name**||

Also, in order to get additional debug messages and understand the issuer root cause, please do the following:
- On your Homebridge instance, open a shell and locate the place where the "index.js" plugin file is stored, for instance: `sudo find / -type f -wholename "*/homebridge-micronova-agua-iot-stove/index.js"`. You should get a found location such as `/usr/lib/node_modules/homebridge-micronova-agua-iot-stove/index.js` 
- Backup the found file, by copying it somewhere else, eg.: `sudo cp /usr/lib/node_modules/homebridge-micronova-agua-iot-stove/index.js /usr/lib/node_modules/homebridge-micronova-agua-iot-stove/index.js.bak` 
- Overwrite the found file with [the one attached here (index.txt)](https://github.com/securechicken/homebridge-micronova-agua-iot-stove/files/6395297/index.txt). Depending on your environment, if you stored the attached file in your Unix home, this could be done with: `sudo cp ~/index.txt /usr/lib/node_modules/homebridge-micronova-agua-iot-stove/index.js`
- Restart your Homebridge instance (or only the plugin child bridge if you set one up), enable Debug for the plugin if you did not already, and copy log messages containing `_getAPIStoveDevicesList/BRUFAL-5` in your reply here.

As a side-note (but an important one):
- Do not hijack closed issues to get in touch with other users: visit their profile page to check if and how they can be reached.
- Please avoid several chained posts for the same issue while you are still the only participant: edit your previous post and add missing information if required. 
- Preferably post correctly formatted text instead of screenshots for command lines and log lines. Take time to read documentation on GitHub and Markdown if you need. Thanks having provided relevant debug information though. The second was useful, but has been removed because it contained authentication secrets.
No biggie, you are probably new to GitHub.

Thanks!

**Comment by brufal** [comment] 2021-04-29 21:23
Hi @securechicken,

First thanks to take time to help me with my problem.
To give you some part of answer :

> Item	Your information
> **Homebridge Version**	V 1.3.4
> **Plugin version**	1.0.0
> **Stove brand : Piazzetta / mobile app name : My Piazzetta

I'm sorry but i have try many of your cmd in my terminal, but i can't fin the file location, can you show me with some screenshot of what you type and where.

I just start on Raspberry ans especially in hombridge. ;-)

**Comment by securechicken** [comment] 2021-04-30 22:01
Dear @brufal,

I won't be able to help you find files on your own environment, plus this would be way out of scope: the better I can do from this plugin perspective and on free time is providing a patched version of the main plugin file (index.js) that will allow you to display more debug messages, and may help us understand what is going wrong with your initial issue.
The general approach to do this is to replace the plugin main file "index.js" with the one I provided on the previous post, and reload the plugin/Homebridge; the commands I gave are just examples, and must be adapted to your environment.
In order to replace the required file, you first have to find where the plugin is located on your Homebridge environment, by connecting to its system shell (you mentioned Raspberry Pi, so I suppose it's Raspbian, which would work a lot like a "Debian" GNU/Linux - you most probably need to connect to the system with SSH first).

You might find useful information on your own environment and Homebridge by reading their documentation/wiki and asking their Internet users communities if any; as well as useful information on Debian GNU/Linux commands by typing their name on a search engine.

**Comment by securechicken** [comment] 2021-05-17 22:23
Please @brufal try again with v1.0.1, enabling DEBUG for plugin, and copy/paste log lines starting like `[YourStoveName] [DEBUG] _getAPIStoveDevicesList checking device from API: [...]` here if you still have the issue.

**Comment by brufal** [comment] 2021-06-05 16:13
Hi @securechicken sorry i was out of my house for a long time.

I will try to get all you talk to me, but i think i need to work more on my rapsberry to understand where i need to go before  do something wrong.

**Comment by brufal** [comment] 2021-06-08 16:38
Hi @securechicken see below the DEBUG with the last update you talk to me : 
[08/06/2021, 18:36:45] [Maison] [DEBUG] _setAPILogin got a OK response
[08/06/2021, 18:36:45] [Maison] [DEBUG] _setAPILogin got JWT token decoded as: {"id":"BFE369C0-939D-4340-94F3-6E84AFDFBDBE","jwtid":"f258883c-745a-4393-a326-48c713c4d7ec","email":"$2y$10$A31JwXyzzYHrqGAeXTBW0ur2nXq1m43edgLF/UT./9m.A7DsGKQQ2","customer_code":"458632","id_app":"3d8eb72a-4845-42c7-bc29-5281d574985e","id_brand":"1","iat":1623170204,"exp":1623256604}
[08/06/2021, 18:36:45] [Maison] _setAPILogin successfully logged-in, setting auto-login refresh job every 86391778 ms
[08/06/2021, 18:36:45] [Maison] [DEBUG] _sendAPIRequest POST to: https://piazzetta.agua-iot.com/deviceList, DATA = null
[08/06/2021, 18:36:45] [Maison] [DEBUG] _sendAPIRequest got a response with OK status
[08/06/2021, 18:36:45] [Maison] [DEBUG] _getAPIStoveDevicesList checking device from API: {"id":"E508EF8A-A00C-4473-A733-17416E9A2CE3","id_device":"3CF9746B-E0CA-4162-91CC-49A4136D73A7","id_product":"66D66637-557F-4DB2-B8B0-D260F0281608","id_client":"BFE369C0-939D-4340-94F3-6E84AFDFBDBE","id_app":null,"product_serial":"11556363","name":"Poêle maison","description":"Maison","mac":"C44F33041639","security_code":"58307075","assistance_code":"      ","country":"FR","state":"Nord","city":"Malincourt","creation_date":"2020-06-26T07:25:18.097Z","update_date":"2021-04-27T20:06:05.897Z","autorization_it":false,"is_online":true,"last_login_date":"2021-06-07T22:09:50.337Z","last_logout_date":"2021-05-31T03:48:30.477Z","cod_art":"P963 18.0","serial":"P963 18.0","name_product":"P963 18.0"}
[08/06/2021, 18:36:45] [Maison] init could not retrieve required stove info from API: _getAPIStoveDevice could not retrieve selected device (Maison) from API devices list: _getAPIStoveDevicesList did not find stove name in API - PLEASE FIX THIS PLUGIN CONFIG VALUE & RESTART: Maison

**Comment by securechicken** [comment] 2021-06-08 17:23
Hi @brufal,
Fixed your post to remove confidential and personal data from it (IDs, your location, date you put the stove in service, etc.); you should pay extra attention and carefully read what you post on the Internet in order to avoid this as much as possible.

Other than that... from these logs messages, the issue seems quite explicit now:

> ```
> ...checking device from API: {[REDACTED],"name":"Poêle maison","description":"Maison",[REDACTED]}
> ...
> ...did not find stove name in API - PLEASE FIX THIS PLUGIN CONFIG VALUE & RESTART: Maison
> ```

**"name":"Poêle maison"**: you put "Maison" in config, not "Poêle maison".

**Comment by brufal** [comment] 2021-06-08 17:45
[08/06/2021, 18:52:23] [Maison] [DEBUG] _setAPILogin got a OK response
[08/06/2021, 18:52:23] [Maison] [DEBUG] _setAPILogin got JWT token decoded as: {"id":"*********","jwtid":"f*******","email":"********","customer_code":"******","id_app":"*********","id_brand":"1","iat":********
[08/06/2021, 18:52:23] [Maison] _setAPILogin successfully logged-in, setting auto-login refresh job every 86391870 ms
[08/06/2021, 18:52:23] [Maison] [DEBUG] _sendAPIRequest POST to: https://piazzetta.agua-iot.com/deviceList, DATA = null
[08/06/2021, 18:52:23] [Maison] [DEBUG] _sendAPIRequest got a response with OK status
[08/06/2021, 18:52:23] [Maison] [DEBUG] _getAPIStoveDevicesList checking device from API: {"id":"********","id_device":"3********","id_product":"6*********","id_client":"*************","id_app":null,"product_serial":"*******","name":"Poêle maison","description":"Maison","mac":"******","security_code":"*******","assistance_code":"      ","country":"FR","state":"****","city":"********","creation_date":"2020-06-26T07:25:18.097Z","update_date":"2021-04-27T20:06:05.897Z","autorization_it":false,"is_online":true,"last_login_date":"2021-06-07T22:09:50.337Z","last_logout_date":"2021-05-31T03:48:30.477Z","cod_art":"P963 18.0","serial":"P963 18.0","name_product":"P963 18.0"}
[08/06/2021, 18:52:23] [Maison] init could not retrieve required stove info from API: _getAPIStoveDevice could not retrieve selected device (Maison) from API devices list: _getAPIStoveDevicesList did not find stove name in API - PLEASE FIX THIS PLUGIN CONFIG VALUE & RESTART: Maison




@securechicken this post should be better without all the personnal infos

**Comment by brufal** [comment] 2021-06-08 20:16
@securechicken thanks now it seems all be ok but when i want to put it off i receive this message :
[Poêle maison] setStoveActive stopped by power swing protection: last power change is too close in time (next power state change possible at Tue Jun 08 2021 22:34:46 GMT+0200 (Central European Summer Time))

That's mean i need to wait like 1h between put it on, and put it off? because i receive this message like 1hours before 22:34:46

**Comment by securechicken** [comment] 2021-06-08 20:35
Fine...
As for the rest, start by carefully reading the [information in the main page](https://github.com/securechicken/homebridge-micronova-agua-iot-stove#limitations), and the message you copied itself.

**Closed as completed by securechicken** 2021-06-08 20:35 UTC
Labels: question
