### ISSUE TITLE
MCZ settings

### ISSUE THREAD

**Issue by fastenspy** [securechicken/homebridge-micronova-agua-iot-stove#7] opened 2021-11-01 10:52 UTC
Hello,

I see "MCZ" in the plugin settings. Is it possible to configure an MCZ stove with Maestro module (Model: DOC) ?

**Comment by securechicken** [comment] 2021-11-09 14:20
Duplicate of #6 .
Please answer [the questions](https://github.com/securechicken/homebridge-micronova-agua-iot-stove/issues/6#issuecomment-829499778) in your original issue to start with (which will reopen the issue), and also this is not a bug.

**Closed as completed by securechicken** 2021-11-09 14:20 UTC
Labels: duplicate, question, unsupported-brand
